//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY.PIM.ENTITYMODEL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class InvestmentEntities : DbContext
    {
        public InvestmentEntities()
            : base("name=InvestmentEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PolicyMaster> PolicyMasters { get; set; }
        public virtual DbSet<AccountMaster> AccountMasters { get; set; }
        public virtual DbSet<BankMaster> BankMasters { get; set; }
    
        public virtual ObjectResult<usp_pam_GetBankDetails_Result> usp_pam_GetBankDetails(string bankName)
        {
            var bankNameParameter = bankName != null ?
                new ObjectParameter("bankName", bankName) :
                new ObjectParameter("bankName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_pam_GetBankDetails_Result>("usp_pam_GetBankDetails", bankNameParameter);
        }
    }
}
