//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MY.PIM.ENTITYMODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class PolicyMaster
    {
        public int PolicyId { get; set; }
        public string PolicyName { get; set; }
        public string PolicyType { get; set; }
        public string PolicyNumber { get; set; }
        public System.DateTime PolicyStartDt { get; set; }
        public System.DateTime PolicyMaturityDt { get; set; }
        public Nullable<decimal> PolicyPremiumAmt { get; set; }
        public string PolicyStatus { get; set; }
        public string PolicyPaymentTerm { get; set; }
        public string PolicyMaturity { get; set; }
        public Nullable<decimal> PolicySumAssured { get; set; }
        public string PolicyPaymentFrequency { get; set; }
        public string PolicyUserId { get; set; }
        public string PolicyPassword { get; set; }
        public string PolicyMobile { get; set; }
        public string PolicyWebsite { get; set; }
    }
}
